#!/usr/bin/env sh

if ! [ -x "$(which llvm-config)" ]; then
  echo 'Error: llvm-config is not found.' >&2
  exit 1
fi
INCLUDEDIR=`llvm-config --includedir`
LIBDIR=`llvm-config --libdir`

echo "HEADER_SEARCH_PATHS = \$(inherited) $INCLUDEDIR" > Settings.xcconfig
echo "LIBRARY_SEARCH_PATHS = \$(inherited) $LIBDIR" >> Settings.xcconfig
echo 'OTHER_LDFLAGS = $(inherited) -lLLVM' >> Settings.xcconfig

swift package generate-xcodeproj --xcconfig-overrides Settings.xcconfig
